[package]
name = "gl_painter"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { version = "^1.12", features = ["derive"] }
gl = "^0.14"
paste = "^1.0"
seq-macro = "^0.3"
thiserror = "^1.0"

[dependencies.glsl_preprocess]
path = "glsl_preprocess"
